name: CI/CD Pipeline for user-service

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the 'master' branch

jobs:
  # Job for building, testing, and preparing the app
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Replace with your Python version

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from the requirements file

      # Run tests using pytest (optional, if you have tests)
      - name: Run tests
        run: |
          pytest  # This will run pytest to execute the tests in your repository

  # Job for deploying the app (after passing the build)
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI runner
    needs: build  # Ensure the deploy job runs after the build job is successful

    steps:
      # Checkout code again (needed for the deploy job)
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH keys for deployment
      - name: Set up SSH keys for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ MIIEowIBAAKCAQEAt15LNejybs9ZbOF/b/itq95AaxzswR6VR9B4To4bq6NelqnI
YTCxNwaizhVSDSB11/27Q8Kwz7O0VUqIofyvIxarTL8uLKnnTQS7e+8HUKRZ4r1a
yVfqeCWonY5gthvs7Z4IYDAgnHoRqnjx36NxHmq2eCjX1jaWYKuprYO7nesJ8ZRj
T2YzbfKFesuCjnc/YLOJBUPwc2lVRRL6b9YzJj8uulWaoiKC8880oA4LpMWC8O3p
R1Xi/jIkq8BgIuuutK+izKSZH3biQ3TSjnQaFiO/YUzSr7saETjxuJ9E8PWg3ArS
7u6txBfQ+XDiNjIGiIw3Ftg/p8AGZFae2wwafQIDAQABAoIBAAR/IMrOFkBMDkjk
Wy1x+ey9BoILs4mzfWdwGNh++PXY/YcJotIUprWkgj0ZuoXQxfaUNBGf+7X/wF4e
Lq1YdroecKMqDQYLXXYGCz2bO2gF9RHhdmayehuxCZwo028yBznMe6D8qZcsvHsO
JuBG2qnygjGpB6HyChNUzP8Qu+yjaKwYiiUQB2+0ZqWNQ7sFJTnzjWmkXQM8+GpO
h5yZSDSxBq91xNbsFQXCHtBXiVHbewQQNrfC8H7/+GTwRat7VUquGxlDv31gwYjb
gmmW6vfjLqgq6z8B1G51YuvCVRQDiHJNRup+Dz+3kOpgdlQpzI+33tusM87yzAJh
SXjIHgECgYEA6VvqSms46/1u0FXyS4YphZWOp8Pkf5RMVJ2rMon+DbDcUroHhXlR
u/B54Uw5VwjIAHetnfjopZK/zoo+3OVu7+NF0WeWzHsSNQODyduBWxLMiEjzgLwQ
NlNMdO6v9oBEeGud/xNpaxrdd75a7BJIdwb9MEjnkMVqiz3b9P1C3RcCgYEAySi6
YKLW5hDk9htyWxfhgm7X0CUN9MIN1iZMkpXX8oZSmsp/hYuAJidK+AhXag0Q+y73
f0ZgB98yAhehPR6+Uj/hiNub+ufAmikw8BlkJN34uK918clfTDEITZj01jVEaX30
tFGqgVDrzikGjptlewRAPpgSdwT2kUOC+GdxyYsCgYACF/0GJegg1elEnUDLRKzi
sfDRuIQ4UNBOggujLHHHFaskYt7mZ6xAD2xIhTKOgVmqB2jbXfxYX/SwmbTurnBM
XrGlq1RDCWekah+ok/uZIZYMMvtcUFOk6SJqeinCAGyc1/pW64mqmFccV+zg6VkV
GE71O/I37k2Cak+q5wrOiQKBgAMIVib2zX6SaqE7MLIm3gN1YFOG+3rhIgxEb4sW
Lzc8xyoGO33r6HaqyPqMRaUXpVXkE18b1H7J4psdeBTPzda3l9LUXLmfnMu2K0Kz
X0se/YzrOD/45TLk2lcxIx/HlcxxVasSQBvK+IMXIz4rIZCFM+K9sCmTLZRrDCJq
jNCZAoGBALPaIMRvpmx8BeOvB7MNata9AhxckFVtnYeDVylw199zHCGeRYf4Teww
0W/tDCoEMPaA+e2Gb+3reezvH+5tD5CRB/JwBR1mZxXWB+yqUdYi8ZyVVg4doHU0
qRpC8t8pWXpug98u+Sn9ZEVToQdyfyZg4FwKxwpgI2A6Q0X9gKHZ
 }}  # Use the secret you added earlier

      # Deploy to production
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
            cd /path/to/your/service  # Navigate to your app directory
            git pull origin master     # Pull the latest changes from the master branch
            systemctl restart user-service  # Restart the service or apply other deployment steps
          EOF
