# This is a CI/CD pipeline for the Python-based user-service project

name: CI/CD Pipeline for user-service (Python)

# Trigger the pipeline on push and pull_request events
on:
  push:
    branches:
      - main  # Trigger the pipeline on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the 'main' branch

jobs:
  # Build and Test Job: Install dependencies, run tests
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the CI runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (specify the version you are using)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip to ensure we are using the latest version
          pip install -r requirements.txt  # Install dependencies listed in requirements.txt

      # Run tests (using pytest)
      - name: Run tests
        run: |
          pytest  # Run your tests using pytest or any other test framework you are using

  # Deploy Job: Deploy to production (or staging) environment
  deploy:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the CI runner
    needs: build  # Ensure deployment runs only after the build job finishes

    steps:
      # Checkout code again (required for the deploy job)
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH keys (use GitHub Secrets for security)
      - name: Set up SSH keys
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key to GitHub Secrets

      # Deploy to production (using SSH or cloud CLI tools)
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
            cd /path/to/your/service
            git pull origin main
            # Restart your application or perform other deployment tasks
            systemctl restart user-service  # Or any deployment-specific command
          EOF
