name: CI/CD Pipeline for user-service

# Trigger the pipeline on push or pull request to the 'main' branch
on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the 'main' branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the 'main' branch

jobs:
  # Job for building, testing, and preparing the app
  build:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Use Python 3.9 (or any version you require)

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from the requirements file

      # Run tests using unittest or another framework (unittest example here)
      - name: Run tests
        run: |
          python -m unittest discover tests  # Adjust the 'tests' directory if your tests are in another folder

  # Job for deploying the app (after passing the build)
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu for the CI runner
    needs: build  # Make sure this runs only after the 'build' job is successful

    steps:
      # Checkout code again (needed for the deploy job)
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH keys for deployment (you must add these to GitHub secrets)
      - name: Set up SSH keys for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key to GitHub Secrets

      # Deploy to the production server or cloud service
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
            cd /path/to/your/service  # Navigate to your app directory
            git pull origin main      # Pull the latest changes from the main branch
            systemctl restart user-service  # Restart the service or apply other deployment steps
          EOF
