name: CI/CD Pipeline for user-service

on:
  push:
    branches:
      - master  # Trigger the pipeline on push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the 'master' branch

jobs:
  # Build and Test Job: Install dependencies, run tests
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu image for the CI runner

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Replace with your Python version

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install all dependencies listed in requirements.txt
          pip install pytest  # Explicitly install pytest in the environment

      # Run tests using pytest
      - name: Run tests
        run: |
          pytest  # This will run pytest to execute the tests in your repository
