name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Trigger the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH keys for authentication
      - name: Set up SSH key
        run: |
          # Create the .ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          
          # Write the SSH private key from the secret into a file
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          
          # Set correct permissions for the SSH private key
          chmod 600 ~/.ssh/id_rsa
          
          # Add the host key of the server to known hosts to prevent SSH asking to verify it
          ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

      # Step 3: Deploy to production
      - name: Deploy to production
        run: |
          ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
            # Navigate to your app directory
            cd /path/to/your/service
            
            # Pull the latest changes from the 'main' branch
            git pull origin master

            # Restart the service (adjust to your specific service name and setup)
            systemctl restart your-service-name
            
            # You can add other deployment steps here (e.g., npm install, etc.)
          EOF
