name: CI/CD Pipeline

on:
  push:
    branches:
      - master   # Trigger the workflow on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use an Ubuntu-based runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up SSH keys for authentication
      - name: Set up SSH key
        run: |
          echo "Creating .ssh directory"
          mkdir -p ~/.ssh  # Ensure the .ssh directory exists
          
          echo "Saving SSH private key to id_rsa"
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa  # Write the SSH private key to file
          
          # Debugging: Check contents of .ssh directory and private key permissions
          ls -la ~/.ssh
          cat ~/.ssh/id_rsa  # Ensure the private key is written correctly (be cautious about security)
          
          echo "Setting correct permissions for the SSH private key"
          chmod 600 ~/.ssh/id_rsa  # Set correct permissions for the private key
          
          echo "Adding the host key to known hosts"
          ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts  # Add the server's SSH key to known hosts

      # Step 3: Deploy to production (master node)
      - name: Deploy to production (Master Node)
        run: |
          echo "Starting SSH connection to the master node"
          ssh -o StrictHostKeyChecking=no user@your-server.com << 'EOF'
            # Navigate to the app directory on the master node
            cd /path/to/your/service  # Update the path to your service

            # Pull the latest changes from the main branch
            git pull origin master  # Make sure to use 'main' branch, or 'master' if required

            # Restart the service to apply changes
            systemctl restart your-service-name  # Update with your actual service name
          EOF
